### ISSUE TITLE
nrf52840 build failed : cannot open openthread submodule files, during tar extraction

### ISSUE THREAD

**Issue by siddhesh-grl** [openthread/ot-reference-release#12]
I was trying to build the latest otbr image, using the ot-reference-release commit `3daef11`
After cloning  the main repo, and updating the submodules I ran the `make-reference-release.bash` script.

Command used for running the build : 
`REFERENCE_PLATFORM=nrf52840 REFERENCE_RELEASE_TYPE=1.3 IN_CHINA=0 ./script/make-reference-release.bash`

Build Error :
`tar: ot-nrf528xx/openthread/.clang-format: Cannot open: Not a directory`
(This error was observed for all files present in openthread submodule of ot-nrf528xx submodule) 

Attaching herewith , the screenshot of the error

![otbr_image_error](https://user-images.githubusercontent.com/93367257/141462254-52e1e95b-dd6d-47ad-b6a7-2d0d128fdc72.png)

**Comment by LuDuda** [comment]
@siddhesh-grl which OS do you use?

Not sure why i don't see it on my PC, but it seems the issue was introduced with #8 - and `tar` does not work well with symlinks.

This should help, i will file a PR after re-running all the builds locally on clean Ubuntu.

```
diff --git a/script/make-raspbian.bash b/script/make-raspbian.bash
index 8fcf820..ca93840 100755
--- a/script/make-raspbian.bash
+++ b/script/make-raspbian.bash
@@ -64,7 +64,7 @@ main() {
     cd docker-rpi-emu/scripts
     sudo mount --bind /dev/pts "$IMAGE_DIR"/dev/pts
     sudo mkdir -p "$IMAGE_DIR"/home/pi/repo
-    sudo tar xzf "$STAGE_DIR"/repo.tar.gz --strip-components 1 -C "$IMAGE_DIR"/home/pi/repo
+    sudo tar xzf "$STAGE_DIR"/repo.tar.gz --absolute-names --strip-components 1 -C "$IMAGE_DIR"/home/pi/repo
     sudo ./qemu-setup.sh "$IMAGE_DIR"
     sudo chroot "$IMAGE_DIR" /bin/bash /home/pi/repo/script/otbr-setup.bash "${REFERENCE_RELEASE_TYPE?}" "$IN_CHINA" "${REFERENCE_PLATFORM?}"
     sudo chroot "$IMAGE_DIR" /bin/bash /home/pi/repo/script/otbr-cleanup.bash
```

**Comment by siddhesh-grl** [comment]
@LuDuda I can compile the code, with the new changes.
OS Used :
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
