### ISSUE TITLE
ncs build : DNS-SD anycast dataset not found

### ISSUE THREAD

**Issue by siddhesh-grl** [openthread/ot-reference-release#22]
I have built an otbr image with `REFERENCE_PLATFORM=ncs` option, using the following command :
`REFERENCE_PLATFORM=ncs REFERENCE_RELEASE_TYPE=1.3 IN_CHINA=0 ./script/make-reference-release.bash`

I have been working with the SRP server on this build.
As per the 1.3 duckhorn spec (Chapter 14 : 14.3.2), Border Router  must announce its SRP service, using the DNSSD anycast  dataset.
This must be a Service TLV, nested inside of a Network Data TLV.

On checking the wireshark capture, the anycast dataset could not be found.
However, there is a Service TLV (in the Network Data TLV of Child ID response) having the SRP Service data. This TLV is transmitted from the Border Router. The Service TLV however, does not exactly match the anycast dataset. (eg. It does not have the SRP number, or the `THREAD_SERVICE_DATA_DNSSD_ANYCAST` constant. 

Attaching a snapshot of the wireshark capture, showing the Service TLV :

![__________cir](https://user-images.githubusercontent.com/93367257/148717500-117caf1d-128e-4fd7-9c72-810dcfdd5fe0.png)

**Comment by simonlingoogle** [comment]
Note that the current OpenThread implementation adds the SRP Unicast Dataset rather than SRP Anycast Dataset.

**Comment by siddhesh-grl** [comment]
So is there any plan to update it in near future? or
can you link any existing issues dealing with the same topic, so we can follow from there?

**Comment by jwhui** [comment]
Closing stale issue.
