### ISSUE TITLE
ncs build : TREL packets sent over multicast transmission, instead of unicast

### ISSUE THREAD

**Issue by siddhesh-grl** [openthread/ot-reference-release#23]
I have built an otbr image with `REFERENCE_PLATFORM=ncs` option, using the following command :
`REFERENCE_PLATFORM=ncs REFERENCE_RELEASE_TYPE=1.3 IN_CHINA=0 ./script/make-reference-release.bash`

There are TREL packets, in the wireshark capture, when I run the build. 
As per the 1.3 duckhorn spec (Chapter 15 - 15.6.3.3 ), TREL packets must be sent over unicast transmission.
However, the packets in the capture, are sent over multicast transmission.
Also, the packets do not exactly match, with the packet structure in 1.3 duckhorn specification (Chapter 15 - 15.6.2).
eg. there is no extended destination address  in the capture.

**Comment by jwhui** [comment]
@siddhesh-grl , thanks for raising this issue.

The behavior you see is currently expected. The change to use TREL over unicast only was made fairly late in the spec development process. The implementation is currently in https://github.com/openthread/openthread/pull/7125, but is waiting on https://github.com/openthread/ot-br-posix/pull/1109 before merging.

**Comment by siddhesh-grl** [comment]
Thank you for the reply. Closing the issue, as the unicast implementation will be merged later.
