### ISSUE TITLE
Command for registering new OMR prefix not available

### ISSUE THREAD

**Issue by siddhesh-grl** [openthread/ot-reference-release#26]
We are writing test scripts for duckhorn based on the 1.3 Duckhorn Test Plan.
While going through the DuckHorn 2.13 test case (2.13. Thread device address update - Point 8), we came across a requirement of Border Router to register a new OMR prefix in the thread network.

We tried to search for the command, that would register a new OMR prefix, in the README files that come inside of the openthread repository. However, no such command is available in the README.

Is there a way to register a new OMR prefix in the Border Router?
We need the fucntionality to complete the 2.13 test case.

**Comment by simonlingoogle** [comment]
I think this test requires the BR to change the OMR prefix.

Currently, we don't have a command that can change OMR prefix. 

We can add a new reference-device only API (e.g. otBorderRoutingSetOmrPrefix) to address this requirement. 

But this test seems unrelated to OMR prefix changes. We may even use a fake address since the device uses any address that Harness instructs it to use. 

Thoughts? @jwhui

**Comment by jwhui** [comment]
Given that the BR is the DUT in this test, I think we should avoid requiring any special behavior on the BR. I would prefer having a special command on ED_1 to control its IPv6 address and triggering an SRP update.

**Comment by siddhesh-grl** [comment]
We checked for the command that adds IPv6 address on the ED_1. command : `ipaddr add <ipv6 address>`.

**Comment by siddhesh-grl** [comment]
We checked for the command that adds custom ipv6 address on the ED_1 side.
Command : `ipaddr add <custom ip>`
This address can be used in the srp update with the command : 
`srp client host address <custom ip>`
The srp update was sent to the SRP server , and service with new `<custom ip>` is registered in the server.

However, we cannot verify point 8 - pass criteria of the 2.13 test case. (since we are not generating a new OMR prefix, just adding a custom IP)
Point 8 : 
`Registers with a new OMR prefix in the Thread Network Data`
Pass Criteria : 
`BR1_1 MUST register a new OMR Prefix in the Thread Network Data. BR_1’s updated SRP Server information appears in the Thread Network Data.`

**Comment by simonlingoogle** [comment]
OMR prefix change seems not directly related to the testing purpose? Maybe we can remove this pass criteria?

**Comment by jwhui** [comment]
Closing stale issue.
