### ISSUE TITLE
Command to disable SRP, while still keeping the advertisement of SRP service 

### ISSUE THREAD

**Issue by siddhesh-grl** [openthread/ot-reference-release#27]
We are writing test scripts for duckhorn based on the 1.3 Duckhorn Test Plan.
While going through the DuckHorn 3.2 test case (3.2. Unresponsive BR - Multiple BRs - Point 12), we came across a requirement.

Requirement (Point 12 of the test case):
*Harness instructs the device to stop listening (??) but continue to advertise SRP service*

We tried below command to disable the SRP service :
`srp server disable`

However, on running the `netdata show` command, the SRP service **(5d)** does not show up after the disable.
Attaching a screenshot of before and after running the `srp server disable`. 

![netdatasrp_LI (2)](https://user-images.githubusercontent.com/93367257/155687009-c3176ca7-dbcc-4257-b473-fb0e880d4cb0.jpg)

Is there a way to stop/disable the SRP service, while it still continues to advertise in the network data?
We need the functionality to complete the 3.2 test case.

**Comment by simonlingoogle** [comment]
Currently, there is no command for doing that. 

Can we instead `reset` the BR device so that the SRP service is still in Network Data, but the SRP server is not responsive.

**Comment by siddhesh-grl** [comment]
We  did a reset on the BR and checked the `netdata show` command. The SRP (5d) service is still present in the network data.

**Comment by siddhesh-grl** [comment]
We did a reset on the BR and checked the `netdata show` command on the cli dongle.
While the SRP server is stopped on the OTBR, the `netdata show` command still has an entry for SRP (5d) service.
Verified the functionality in the 3.2 test case also.

**Comment by jwhui** [comment]
Closing stale issue.
