### ISSUE TITLE
ncs Build: 404 Error Occuring

### ISSUE THREAD

**Issue by shouvik-grl** [openthread/ot-reference-release#39]
We have built an otbr image with `REFERENCE_PLATFORM=ncs` option, using the following command :
`REFERENCE_PLATFORM=ncs REFERENCE_RELEASE_TYPE=1.3 IN_CHINA=0 ./script/make-reference-release.bash`

We are getting the following Error:
![Screenshot from 2022-11-10 18-31-37](https://user-images.githubusercontent.com/103411752/201099714-1871f4bd-9d0b-4507-8210-979d7b4ada56.png)

[The Link ](https://opensource.apple.com/tarballs/mDNSResponder/mDNSResponder-1310.80.1.tar.gz) 
We tried in the browser, But getting the 404 error in browser also.
![404](https://user-images.githubusercontent.com/103411752/201100539-58c4eedd-1689-40f5-829e-a68f562baf2d.png)

**Comment by jwhui** [comment]
@shouvik-grl , thanks for raising this issue. I submitted #40 to address this issue.
