### ISSUE TITLE
Command to change DNS Server Port at Runtime Not Available

### ISSUE THREAD

**Issue by shouvik-grl** [openthread/ot-reference-release#47]
We are writing test scripts for duckhorn based on the 1.3 Duckhorn Test Plan.
While going through the DuckHorn 3.2 test case (3.2. [COMPONENT]  Re-register service with active SRP server - Multiple BRs - With AIL) and 3.2b test case (3.2b. [PRODUCT] Re-register service with active SRP server - Multiple BRs - With AIL - Thread Product DUT) , we came across a requirement.

In Step 4 (for both the test cases Step 4) it is advised to configure the BR "_to advertise its DNS/SRP Unicast Dataset at an available port value, P, different from 53._"
In step 8 (3.2b) it is advised to again change the port "_BR to advertise its DNS/SRP Unicast Dataset at a new port value, P2_."

We could not found a suitable command for that.

Is it possible to change this port at the runtime?

**Comment by abtink** [comment]
Disabling the SRP server and enable it again will do this. SRP server will pick a new port number upon restart.
CLI command `srp server disable` and then `srp server enable` (which map to `otSrpServerSetEnabled()` API).

**Comment by librasungirl** [comment]
One supplement is only when there are SRP services registered, the DNS/SRP port that is registered into the Thread Network Data will be stored into non-volatile storage and increase in next stack restart or `srp server disable/enable`

The default SRP port for OTBR reference is [53535](https://github.com/openthread/openthread/blob/main/src/core/config/srp_server.h#L70) (different from 53 as step4 requires) and there is DUT's SRP service registered before step8,  with `srp server disable/enable` on BR, the port will increase as the test requires.

**Comment by shouvik-grl** [comment]
Thanks @abtink and @librasungirl for your support.

I tried the same i.e: disabling the SRP server (`srp server disable`) and then again enabling it (`srp server enable`)

But its looking like not working for me
![SRPPortNotChangingSS](https://user-images.githubusercontent.com/103411752/217544761-b2bef1e6-a9b5-4bdf-ae67-526be07d68f6.png)

Am I doing something wrong?

**Comment by librasungirl** [comment]
@shouvik-grl as mentioned above, you need to bring up one thread device and let it register some SRP service to the BR. then disable and enable srp server, you will find the port increases.

**Comment by shouvik-grl** [comment]
Thanks for your support @librasungirl 

Yes with the thread device register some SRP service to the BR
SRP port change is working.
![srp port change working](https://user-images.githubusercontent.com/103411752/217798583-510e1adc-8dbe-4296-950f-17116f5efa2d.png)


Again thanks @abtink  and @librasungirl  for your sopport.
