### ISSUE TITLE
MLE Data Response Not Sent

### ISSUE THREAD

**Issue by shouvik-grl** [openthread/ot-reference-release#48]
We are writing test scripts for duckhorn based on the 1.3 Duckhorn Test Plan.
While going through the DuckHorn 1.1 test case (1.1. Reachability - Single BR / Single Infrastructure Link), it is advised to check few TLVs in the step3 in the MLE Data Response and in the step4 it is advised to check the _'ICMPv6 ND Router Advertisements'_

But unfortunately in the latest build both of these packets are missing in the capture file.

The commit We are using for the [ot-reference-release](https://github.com/openthread/ot-reference-release) is d6f079d
Its a NCS Build.

The Capture file is attached for the Ready reference

[Fail_OTNCS13_BR_DH_1_1_BR_1_v57.3_2023_02_07-18_53_56_Ch-13.zip](https://github.com/openthread/ot-reference-release/files/10677506/Fail_OTNCS13_BR_DH_1_1_BR_1_v57.3_2023_02_07-18_53_56_Ch-13.zip)

**Comment by jwhui** [comment]
It appears that the packet capture is not capturing some of the earlier packets. For example, the first MLE packet that I see is a Child ID Request. The MLE Parent Request / Parent response exchange initiated by the child is not captured. Before that, we should see MLE messages from the BR as it transitions from being detached to becoming a leader.

**Comment by shouvik-grl** [comment]
Thanks @jwhui for your insight, 

This looks like a internal THCI issue. We solved it and closing the ticket.

The capture is attached for reference.
[Pass_OTNCS13_BR_DH_1_1_BR_1_v57.3_2023_02_13-16_49_06_Ch-13.zip](https://github.com/openthread/ot-reference-release/files/10722660/Pass_OTNCS13_BR_DH_1_1_BR_1_v57.3_2023_02_13-16_49_06_Ch-13.zip)
