### ISSUE TITLE
TREL enabling failed in NCS 1.3 Build

### ISSUE THREAD

**Issue by shouvik-grl** [openthread/ot-reference-release#49]
We are trying to make a NCS build with the TREL functionality.

For that we added the TREL flag `CONFIG_OPENTHREAD_RADIO_LINK_TREL_ENABLE=y` in the config/ncs/overlay-cli-1_3.conf and config/ncs/overlay-rcp-1_3.conf files

During the 1.3 build we are getting error (Error log attached).
[TRELBuildErrorLog.zip](https://github.com/openthread/ot-reference-release/files/11148446/TRELBuildErrorLog.zip)

The command for the build we are using is: `REFERENCE_PLATFORM=ncs  REFERENCE_RELEASE_TYPE=1.3  IN_CHINA=0 ./script/make-reference-release.bash`

**Comment by canisLupus1313** [comment]
@shouvik-grl if You remove `CONFIG_OPENTHREAD_RADIO_LINK_TREL_ENABLE=y` from `config/ncs/overlay-cli-1_3.conf`

**Comment by shouvik-grl** [comment]
@canisLupus1313  
We already tried with that. But, no [TREL related commands](https://github.com/openthread/openthread/tree/c6179c24ed75a11c14dc4b1fffcde58be0bda785/src/cli#trel)  are working. All are throwing error.

**Comment by sam-grl** [comment]
@canisLupus1313  After removing CONFIG_OPENTHREAD_RADIO_LINK_TREL_ENABLE=y from config/ncs/overlay-cli-1_3.conf are getting a new error.

**Comment by sam-grl** [comment]
@canisLupus1313  After removing CONFIG_OPENTHREAD_RADIO_LINK_TREL_ENABLE=y from config/ncs/overlay-cli-1_3.conf .   we are getting a new error, attaching the error log with this.                   
[TREL_BUILD_LOG_ERROR.zip](https://github.com/openthread/ot-reference-release/files/11188267/TREL_BUILD_LOG_ERROR.zip)

**Comment by shouvik-grl** [comment]
@canisLupus1313 
OTBR image (Pi image) building process was unsuccessful.
We tried 3 times and every time got same issue.

**Comment by canisLupus1313** [comment]
@shouvik-grl This looks like problems with internet connectivity.
```
Get:2 http://archive.raspberrypi.org/debian buster/main armhf python-pip-whl all 18.1-5+rpt1 [1591 kB]
Err:1 http://raspbian.mirror.net.in/raspbian/raspbian buster/main armhf libcurl3-gnutls armhf 7.64.0-4+deb10u5
  Connection failed [IP: 103.195.68.3 80]
Err:3 http://raspbian.mirror.net.in/raspbian/raspbian buster/main armhf liberror-perl all 0.17027-2
  Connection failed [IP: 103.195.68.3 80]
Err:4 http://raspbian.mirror.net.in/raspbian/raspbian buster/main armhf git-man all 1:2.20.1-2+deb10u8
  Connection failed [IP: 103.195.68.3 80]
Err:5 http://raspbian.mirror.net.in/raspbian/raspbian buster/main armhf git armhf 1:2.20.1-2+deb10u8
  Connection failed [IP: 103.195.68.3 80]
Get:6 http://archive.raspberrypi.org/debian buster/main armhf python3-pip all 18.1-5+rpt1 [171 kB]
Err:7 http://raspbian.mirror.net.in/raspbian/raspbian buster/main armhf python3-lib2to3 all 3.7.3-1
  Connection failed [IP: 103.195.68.3 80]
Err:8 http://raspbian.mirror.net.in/raspbian/raspbian buster/main armhf python3-distutils all 3.7.3-1
  Connection failed [IP: 103.195.68.3 80]
Fetched 1762 kB in 3s (525 kB/s)
E: Failed to fetch http://raspbian.mirror.net.in/raspbian/raspbian/pool/main/c/curl/libcurl3-gnutls_7.64.0-4+deb10u5_armhf.deb  Connection failed [IP: 103.195.68.3 80]
E: Failed to fetch http://raspbian.mirror.net.in/raspbian/raspbian/pool/main/libe/liberror-perl/liberror-perl_0.17027-2_all.deb  Connection failed [IP: 103.195.68.3 80]
E: Failed to fetch http://raspbian.mirror.net.in/raspbian/raspbian/pool/main/g/git/git-man_2.20.1-2+deb10u8_all.deb  Connection failed [IP: 103.195.68.3 80]
E: Failed to fetch http://raspbian.mirror.net.in/raspbian/raspbian/pool/main/g/git/git_2.20.1-2+deb10u8_armhf.deb  Connection failed [IP: 103.195.68.3 80]
E: Failed to fetch http://raspbian.mirror.net.in/raspbian/raspbian/pool/main/p/python3-stdlib-extensions/python3-lib2to3_3.7.3-1_all.deb  Connection failed [IP: 103.195.68.3 80]
E: Failed to fetch http://raspbian.mirror.net.in/raspbian/raspbian/pool/main/p/python3-stdlib-extensions/python3-distutils_3.7.3-1_all.deb  Connection failed [IP: 103.195.68.3 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
+ cleanup
+ set +e
++ losetup -j /tmp/raspbian/raspbian.img --output NAME -n
```

On my site those are downloaded without a problem can You verify that you are able to update raspbian? Maybe you some proxy or firewall issues?

**Comment by shouvik-grl** [comment]
@canisLupus1313 Thanks for your support

We changed the mirror server from India to Oxford server and after that the, build was successful. [TREL Flag is ON]

But TREL related commands are not working.

I can see a new [PR](https://github.com/openthread/ot-reference-release/pull/51),
Is it related to TREL also?

![TRELCommandErr](https://user-images.githubusercontent.com/103411752/231451173-caf66fd0-71b3-410e-a20c-4057638260b8.png)
![Screenshot 2023-04-12 165625](https://user-images.githubusercontent.com/103411752/231451195-1a5b6ea1-9d89-4ea4-98e2-3090d9290a13.png)

**Comment by sunytt** [comment]
To get TREL enabled you could also try to update the [OTBR_OPTIONS](https://github.com/openthread/ot-reference-release/blob/main/script/otbr-setup.bash#L110), by changing `-DOT_TREL=ON` to `-DOTBR_TREL=ON`   @shouvik-grl
