### ISSUE TITLE
sdk-nrf commit id needs update 

### ISSUE THREAD

**Issue by karthick-grl** [openthread/ot-reference-release#59]
We currently use `ncs` build flag to make reference build for harness nordic testbed. [sdk-nrf-commit](https://github.com/openthread/ot-reference-release/blob/f25846207d5103ef0d1869f8976fd88f8875658b/config/ncs/sdk-nrf-commit#L1) from Nov looks outdated as many significant fixes got into core OT repository after that. Shall we get the commit-id updated?  

When tried locally updating to the latest [commit-id](https://github.com/nrfconnect/sdk-nrf/releases/tag/v2.4.0), build failed due to kconfig error.
![image](https://github.com/openthread/ot-reference-release/assets/12555028/925ec947-96e2-4b3c-af77-e75195e0e992)

@edmont @canisLupus1313 FYI

**Comment by canisLupus1313** [comment]
@karthick-grl  I will take a look into it.
