### ISSUE TITLE
Thread 1.3.1 build failing

### ISSUE THREAD

**Issue by sam-grl** [openthread/ot-reference-release#65]
Error while attempt to build 1.3.1 reference i.e., with flag `REFERENCE_RELEASE_TYPE=1.3.1`. Log screenshot attached below
![1_3_1issue_](https://github.com/openthread/ot-reference-release/assets/109652622/309e51a9-4cb2-4ca8-bb65-7f5c7f9b50d8)

We suspect this could be because 1.3.1 not being handled in ncp_openthread.cpp
https://github.com/openthread/ot-br-posix/blob/358e809e272c5209f333ad1eeed56e3178423f5b/src/ncp/ncp_openthread.cpp#L384.

**Comment by jwhui** [comment]
@sam-grl , thanks for raising this. I just submitted #68, which should address this issue.
