### ISSUE TITLE
sdk-nrf commit ID needs to be updated as the reference devices require the latest TREL updates

### ISSUE THREAD

**Issue by karthick-grl** [openthread/ot-reference-release#69]
Could we obtain the latest OpenThread commit for the [sdk-nrf](https://github.com/openthread/ot-reference-release/blob/main/config/ncs/sdk-nrf-commit) ? The current codebase appears to be at least four months old. Given the substantial updates on the TREL side in OT repo, especially with its high priority for Thread 1.3.1 launch, the harness reference devices require this update.

@canisLupus1313 Is this something you can help us with?

**Comment by canisLupus1313** [comment]
@karthick-grl  please check #70

**Comment by karthick-grl** [comment]
Thanks for quick turn around @canisLupus1313 . Will try to make a build on our side for 1.3 reference.
