### ISSUE TITLE
sdk-nrf : `CONFIG_OPENTHREAD_BLE_TCAT` kconfig flag error. Require latest commit id?

### ISSUE THREAD

**Issue by karthick-grl** [openthread/ot-reference-release#72]
Error while attempting build `ncs` with TCAT kconfig flag enabled [CONFIG_OPENTHREAD_BLE_TCAT](CONFIG_OPENTHREAD_BLE_TCAT), will updating to latest sdk-nrf commit help? @canisLupus1313 
![image](https://github.com/openthread/ot-reference-release/assets/12555028/95d4e493-6ff4-41b3-8d67-b2ddaad3da88)

**Comment by canisLupus1313** [comment]
@karthick-grl Yes this flag and functionality is in never ncs. Unfortunatelly we currently are facing with few major bugs (also affecting certification) so I can update this repo when those will be resolved.

**Comment by canisLupus1313** [comment]
@karthick-grl  I have new EXPERIMENTAL version of reference SW where I can upload it for You?

**Comment by karthick-grl** [comment]
@canisLupus1313 Will share you a google drive space offline.

**Comment by canisLupus1313** [comment]
@karthick-grl  I have uploaded the packages.

**Comment by karthick-grl** [comment]
Acknowledged! Thanks for the help @canisLupus1313

**Comment by canisLupus1313** [comment]
I would say it's up to you. Currently wye are working on few major changes in NSC so the bump wont happen soon in this repo.

**Comment by canisLupus1313** [comment]
@karthick-grl  Requested update of NCS #73
